### ISSUE TITLE
Can't use multiple pizza plots in a single figure

### ISSUE THREAD

**Issue by hghws03** [andrewRowlinson/mplsoccer#105]
When I try to use the ax parameter in make_pizza() (_e.g_ ax=axs[2]), I always get the following message: 

"AttributeError: 'Axes' object has no attribute 'set_rorigin'"

This means I can only plot a pizza plot on another figure, not on a figure with multiple axes. I can add code examples if needed, but since I've tested this multiple times, I figured it isn't required.

**Comment by andrewRowlinson** [comment]
This is definitely possible, I think you may be trying to plot pizza plots on a non-polar axes. See the example here for how to do this: https://github.com/andrewRowlinson/data-science/blob/master/football/multiple_pizza_plots.ipynb

**Comment by andrewRowlinson** [comment]
This is definitely possible, I think you may be trying to plot pizza plots on a non-polar axes. See the example here for how to do this: https://github.com/andrewRowlinson/data-science/blob/master/football/multiple_pizza_plots.ipynb
