### ISSUE TITLE
Statsbomb  location now  includes x,y,z for some eventes like shots

### ISSUE THREAD

**Issue by davidfombella** [andrewRowlinson/mplsoccer#18]
Hi Andrew:

Just checking this easy to fix problem, 
 read_event(f'match_id.json', warn=False)

`    157     # split location info to x, y and (z for shot) columns and drop old columns
--> 158     _split_location_cols(df, 'location', ['x', 'y'])

## Error output
ValueError: 2 columns passed, passed data had 3 columns
`

**Comment by andrewRowlinson** [comment]
Fixed with #19 - added extra 'z' coordinate for splitting the location.

**Comment by andrewRowlinson** [comment]
Fixed with #19 - added extra 'z' coordinate for splitting the location.
