### ISSUE TITLE
Feature requests: Lines from the labels to the center and comparison of more than two data sets

### ISSUE THREAD

**Issue by darinkist** [andrewRowlinson/mplsoccer#51]
Hi - The easy and pragmatic way of creating radar charts is quite impressive!

So far, I am missing two features:

1. Lines from the param labels to the center like this one here:
![radar-chart](https://user-images.githubusercontent.com/62692170/173205664-1f4a24f3-320a-4330-842d-c268a7adaa4f.png)
2. Option to compare more than 2 (players) within one radar char

**Comment by andrewRowlinson** [comment]
Glad you like it. You can already do number 2 with the current functionality. It's not well documented though:

`import matplotlib.pyplot as plt
import numpy as np
from mplsoccer import Radar

# parameter names of the statistics we want to show
params = ["npxG", "Non-Penalty Goals", "xA", "Key Passes", "Through Balls",
          "Progressive Passes", "Shot-Creating Actions", "Goal-Creating Actions",
          "Dribbles Completed", "Pressure Regains", "Touches In Box"]

# The lower and upper boundaries for the statistics
low =  [0.08, 0.0, 0.1, 1, 0.6,  4, 3, 0.3, 0.3, 2.0, 2]
high = [0.37, 0.6, 0.6, 4, 1.2, 10, 8, 1.3, 1.5, 5.5, 5]

bruno_values =  [0.25, 0.42, 0.42, 3.47, 1.04, 8.06, 5.62, 0.97, 0.56, 5.14, 3.54]
bruyne_values = [0.32, 0.00, 0.43, 3.50, 0.98, 7.72, 6.18, 0.98, 1.71, 4.88, 4.96]
new_player = np.minimum(bruno_values, bruyne_values) + np.abs(np.array(bruno_values) - np.array(bruyne_values)) / 2

radar = Radar(params, low, high,
              # whether to round any of the labels to integers instead of decimal places
              round_int=[False]*11,
              num_rings=4,  # the number of concentric circles (excluding center circle)
              # if the ring_width is more than the center_circle_radius then
              # the center circle radius will be wider than the width of the concentric circles
              ring_width=1, center_circle_radius=1)

fig, ax = radar.setup_axis()  # format axis as a radar
rings_inner = radar.draw_circles(ax=ax, facecolor='None', edgecolor='black')  # draw circles
radar_output = radar.draw_radar(bruno_values, ax=ax,
                                kwargs_radar={'facecolor': '#9350a1', 'alpha': 0.4},
                                kwargs_rings={'facecolor': 'None'})  # draw the radar
radar_output = radar.draw_radar(bruyne_values, ax=ax,
                                kwargs_radar={'facecolor': '#bc7d39', 'alpha': 0.4},
                                kwargs_rings={'facecolor': 'None'})  # draw the radar
radar_output = radar.draw_radar(new_player, ax=ax,
                                kwargs_radar={'facecolor': '#697ed5', 'alpha': 0.4},
                                kwargs_rings={'facecolor': 'None'})  # draw the radar
radar_poly, rings_outer, vertices = radar_output
range_labels = radar.draw_range_labels(ax=ax, fontsize=15)  # draw the range labels
param_labels = radar.draw_param_labels(ax=ax, fontsize=15)  # draw the param labels
`

**Comment by andrewRowlinson** [comment]
You can't do number 1 with the current API, I can look at adding it, but here is a working example for the meantime:

```
import matplotlib.pyplot as plt
import numpy as np
from mplsoccer import Radar

# parameter names of the statistics we want to show
params = ["npxG", "Non-Penalty Goals", "xA", "Key Passes", "Through Balls",
          "Progressive Passes", "Shot-Creating Actions", "Goal-Creating Actions",
          "Dribbles Completed", "Pressure Regains", "Touches In Box"]

# The lower and upper boundaries for the statistics
low =  [0.08, 0.0, 0.1, 1, 0.6,  4, 3, 0.3, 0.3, 2.0, 2]
high = [0.37, 0.6, 0.6, 4, 1.2, 10, 8, 1.3, 1.5, 5.5, 5]

bruno_values =  [0.25, 0.42, 0.42, 3.47, 1.04, 8.06, 5.62, 0.97, 0.56, 5.14, 3.54]
bruyne_values = [0.32, 0.00, 0.43, 3.50, 0.98, 7.72, 6.18, 0.98, 1.71, 4.88, 4.96]
new_player = np.minimum(bruno_values, bruyne_values) + np.abs(np.array(bruno_values) - np.array(bruyne_values)) / 2

radar = Radar(params, low, high,
              # whether to round any of the labels to integers instead of decimal places
              round_int=[False]*11,
              num_rings=4,  # the number of concentric circles (excluding center circle)
              # if the ring_width is more than the center_circle_radius then
              # the center circle radius will be wider than the width of the concentric circles
              ring_width=1, center_circle_radius=1)

fig, ax = radar.setup_axis()  # format axis as a radar
rings_inner = radar.draw_circles(ax=ax, facecolor='None', edgecolor='black')  # draw circles
radar_output = radar.draw_radar(bruno_values, ax=ax,
                                kwargs_radar={'facecolor': '#9350a1', 'alpha': 0.4},
                                kwargs_rings={'facecolor': 'None'})  # draw the radar
radar_output = radar.draw_radar(bruyne_values, ax=ax,
                                kwargs_radar={'facecolor': '#bc7d39', 'alpha': 0.4},
                                kwargs_rings={'facecolor': 'None'})  # draw the radar
radar_output = radar.draw_radar(new_player, ax=ax,
                                kwargs_radar={'facecolor': '#697ed5', 'alpha': 0.4},
                                kwargs_rings={'facecolor': 'None'})  # draw the radar
radar_poly, rings_outer, vertices = radar_output
range_labels = radar.draw_range_labels(ax=ax, fontsize=15)  # draw the range labels
param_labels = radar.draw_param_labels(ax=ax, fontsize=15)  # draw the param labels

# add lines
outer_ring = radar.center_circle_radius + (radar.ring_width * radar.num_rings)
param_xs = outer_ring * radar.rotation_sin
param_ys = outer_ring * radar.rotation_cos
for i in range(len(param_xs)):
  ax.plot([0, param_xs[i]], [0, param_ys[i]], color='black')
```

![image](https://user-images.githubusercontent.com/33607496/173247357-9a4b4828-d556-495a-960c-ac33b95f3479.png)

**Comment by andrewRowlinson** [comment]
I have added the lines from the center to the edges for the next release as the spoke method.

https://github.com/andrewRowlinson/mplsoccer/blob/f5a8fcc49cc88437adad069a5f4db5beff6be4fc/mplsoccer/radar_chart.py#L471-L512

I hope to release it soon.

**Comment by andrewRowlinson** [comment]
This is released now on pypi.
