### ISSUE TITLE
Missing parenthesis - Statsbomb.py - Read_Lineup - Getting Match_ID - TypeError: 'PosixPath' object is not subscriptable

### ISSUE THREAD

**Issue by pakkk** [andrewRowlinson/mplsoccer#54]
Hi,

There is a bug in Statsbomb.py (function "read_lineup") in the following line:

match_id = os.path.basename(path_or_buf[:-5])

It should be:

match_id = os.path.basename(path_or_buf)[:-5]

The current exception is "TypeError: 'PosixPath' object is not subscriptable"

My Python version is 3.7.3

Thank you!

**Comment by andrewRowlinson** [comment]
Thanks fixed with f76720076a534ba28d35a22bb0c34826a262b27f

I am considering removing the ability to read from local files in favour of just reading from the API/ open data. Would this be a problem?

**Comment by pakkk** [comment]
Thanks Andrew!

I'm using your code for my Phd. about AI applied to sports :)

I'm not sure to remove the ability to read from local files:

   - Imagine that Statsbomb removes from GitHub the JSON data or Github is
   down temporarily.
   - Reading from local files is faster than downloading from the Internet.
   - The code about reading is only 3 lines in every function.

I take advantage of this email to ask you ... Do you think it would be a
good idea to parse and convert to dataFrame the three-sixty?

Cheers,
Paco.

**Comment by andrewRowlinson** [comment]
I've actually got a branch that parses the data much better: https://github.com/andrewRowlinson/mplsoccer/blob/update_1_0_7/mplsoccer/statsbomb.py

It's faster and also does the 360 data too. I haven't had time to finish the rest of the features. I could add a class to this like Sblocal for parsing local files.

**Comment by pakkk** [comment]
ok, many thanks for your help :)
