### ISSUE TITLE
Any example about how to annotate over the players with Animations?

### ISSUE THREAD

**Issue by pakkk** [andrewRowlinson/mplsoccer#58]
Hi Andrew,

Using StatsBomb and your framework, I am trying to add the following information inside the **animation** function:

- Jersey_number of home and away players, but I cannot achieve it (I got the following exception: AttributeError: 'FuncAnimation' object has no attribute 'annotate')

pitch.annotate('?', (awayTeamXandYPosition.x[i], awayTeamXandYPosition.y[i]),
                       va='center', ha='center', color='white',
                       fontsize=15, ax=ax['pitch'])

- Update the plt title, but I got a similar exception.

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.title.html?highlight=title#matplotlib.pyplot.title

Could you help me?

Thank you!

Cheers,
Paco.

**Comment by pakkk** [comment]
Thank you for your fast response :)

Yes, I tried it, but the pitch is empty (neither players nor text):

I share with you the plot_animation.py in pastebin:

[https://pastebin.com/LEJp2YMr ](https://pastebin.com/LEJp2YMr)

Thanks.

**Comment by pakkk** [comment]
Thank you!!!! I have achieved it ;)

What about the pitch.annotate? Any ideas?

Thanks again!

**Comment by andrewRowlinson** [comment]
I would try Thomas Kuhn's suggestion here:
https://stackoverflow.com/questions/18351932/animate-points-with-labels-with-matplotlib

Would you mind posting your ax.text solution as a reply or adding it to the example as a pull request? It might help some other people.

**Comment by pakkk** [comment]
Thank you!

For the ax.text solution:

- Firstly, I create an instance of that in the init function: self.time_text = self.axis.text(0.5, 0.5, '')
- Secondly, I set the text in the animation function: self.time_text.set_text('Hello world!')
- Finally, animation function returns the Actor "self.time_text"

Cheers,
Paco.

**Comment by pakkk** [comment]
Thank you for your fast response :)

Yes, I tried it, but the pitch is empty (neither players nor text):

I share with you the animation.py in pastebin:

https://pastebin.com/LEJp2YMr  <https://pastebin.com/LEJp2YMr>

Thanks.
