### ISSUE TITLE
Replace setup.py

### ISSUE THREAD

**Issue by andrewRowlinson** [andrewRowlinson/mplsoccer#67]
Replace setup with pyproject.toml and setup.cfg. Add __version__ to init. Use flit or hatch:

https://flit.pypa.io/en/latest/index.html#
https://hatch.pypa.io/latest/

**Comment by ofek** [comment]
Should be easy https://hatch.pypa.io/latest/intro/#existing-project

**Comment by andrewRowlinson** [comment]
Thanks @ofek, that's great!
