### ISSUE TITLE
Trying to install mplsoccer with pip within a Venv and get an error related to Scipy

### ISSUE THREAD

**Issue by resona8e** [andrewRowlinson/mplsoccer#85]
Collecting scipy
  Using cached scipy-1.10.0.tar.gz (42.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      The Meson build system
      Version: 1.0.0
      Source dir: /private/var/folders/hk/4ryb7f7d4ln3rh6dlm3khpcr0000gn/T/pip-install-fjm6g3k5/scipy_091083c83de84fe18f7cfcff51fcbf29
      Build dir: /private/var/folders/hk/4ryb7f7d4ln3rh6dlm3khpcr0000gn/T/pip-install-fjm6g3k5/scipy_091083c83de84fe18f7cfcff51fcbf29/.mesonpy-ju3scbhx/build
      Build type: native build
      Project name: SciPy
      Project version: 1.10.0
      C compiler for the host machine: cc (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")
      C linker for the host machine: cc ld64 450.3
      C++ compiler for the host machine: c++ (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")
      C++ linker for the host machine: c++ ld64 450.3
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: NO
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      Fortran compiler for the host machine: gfortran (gcc 12.2.0 "GNU Fortran (Homebrew GCC 12.2.0) 12.2.0")
      Fortran linker for the host machine: gfortran ld64 530
      Compiler for Fortran supports arguments -Wno-conversion: YES
      Checking if "-Wl,--version-script" : links: NO
      Program cython found: YES (/private/var/folders/hk/4ryb7f7d4ln3rh6dlm3khpcr0000gn/T/pip-build-env-cj4t6m7a/overlay/bin/cython)
      Program python found: YES (/Users/nathaniel/Desktop/futbolSci2/soccerSci2/bin/python3)
      Did not find pkg-config by name 'pkg-config'
      Found Pkg-config: NO
      Program pythran found: YES (/private/var/folders/hk/4ryb7f7d4ln3rh6dlm3khpcr0000gn/T/pip-build-env-cj4t6m7a/overlay/bin/pythran)
      Run-time dependency threads found: YES
      Library npymath found: YES
      Library npyrandom found: YES
      Found CMake: /usr/local/bin/cmake (3.25.2)
      Run-time dependency openblas found: NO (tried pkgconfig, framework and cmake)
      Run-time dependency openblas found: NO (tried framework and cmake)
      
      ../../scipy/meson.build:134:0: ERROR: Dependency lookup for OpenBLAS with method 'pkgconfig' failed: Pkg-config binary for machine 1 not found. Giving up.

**Comment by eli-schwartz** [comment]
The error message says that pip tried to install a dependency -- SciPy -- but SciPy could not be installed from a precompiled wheel because there wasn't one available for your macOS version and python version and hardware.

So it tried to compile SciPy from source, and that didn't work because of the posted message -- you did not have SciPy's dependency on openblas installed.

There's nothing this project can do about that, it's purely a SciPy problem. But have you tried installing openblas from homebrew?

**Comment by resona8e** [comment]
Yes, I just installed openblas with homebrew and am getting the same error. Thank you for responding
