### ISSUE TITLE
Heatmap color coding

### ISSUE THREAD

**Issue by enadol** [andrewRowlinson/mplsoccer#90]
Greetings! This is not an issue but maybe just a comment or quick question. On the heatmap examples, one uses brighter colors for high values...

![image](https://github.com/andrewRowlinson/mplsoccer/assets/5300289/daa28848-4d2a-4df9-af0c-174880a1a2df)

...whereas the next features brighter colors for lower values.

![image](https://github.com/andrewRowlinson/mplsoccer/assets/5300289/bc3a7c75-8d62-4965-9dc5-03322a1b1a86)

Is there a contradicton, or maybe I'm missing something here? Normally I would asume that, in a heatmap, "darker" always means "higher". Thanks in advance and congratulations for mplsoccer, a very useful tool.

**Comment by andrewRowlinson** [comment]
Yup, the first is called hot, and the 'hotter' areas are lighter. I do tend to use darker = larger number if I am using a light background. On dark backgrounds you might want the opposite. All of the matplotlib cmaps can actually be reversed with _r appended to the name.

However, there's no fixed rule. Sometimes you want three colours like this excellent example: https://twitter.com/jonollington/status/1677590743249035264?s=20.

I recommend this great article on colour: https://blog.datawrapper.de/beautifulcolors/. Colour is really important for making great viz!

**Comment by enadol** [comment]
Oh, I totally get it. It makes sense with the dark background. Many thanks also for the articles! Keep it up!
