### ISSUE TITLE
cannot import name 'docstring' from 'matplotlib'

### ISSUE THREAD

**Issue by hadisotudeh** [andrewRowlinson/mplsoccer#96]
When running "from mplsoccer import VerticalPitch", I get:

![image](https://github.com/andrewRowlinson/mplsoccer/assets/2101643/313017c9-bb0b-47da-af41-197aad1ea849)

**Comment by OnlineAnalytics** [comment]
Hi @hadisotudeh , try a roll back of Matplotlib to version 3.7 worked for me.

**Comment by hadisotudeh** [comment]
Hi @OnlineAnalytics,

Thanks, yes that fixes the issue :)

**Comment by andrewRowlinson** [comment]
It looks like matplotlib depreciated this feature. I was using it to copy docstrings to avoid rewriting them everywhere. I need to look for an alternative.

**Comment by andrewRowlinson** [comment]
This should be fixed now with version 1.2.2. Available now on pypi and conda-forge.
