### ISSUE TITLE
Unable to fetch match data 

### ISSUE THREAD

**Issue by RishabAgr** [andrewRowlinson/mplsoccer#97]
I was using the Sbopen parser to fetch data from the Statsbomb database and encountered the following error: 

<img width="770" alt="image" src="https://github.com/andrewRowlinson/mplsoccer/assets/134379486/f1f06ea8-cdae-456f-ab2c-5dfe4b796d68">

My internet connection has been working smoothly, and previous calls to the Statsbomb dataset have been successful, but after this issue arose for the first time, I have been unable to fetch any data at all.

**Comment by andrewRowlinson** [comment]
Can you try again? I cannot replicate this with Google Collab.
![Screenshot_20230927-175015](https://github.com/andrewRowlinson/mplsoccer/assets/33607496/34722a15-fa72-413b-8a28-d35549406e85)

**Comment by andrewRowlinson** [comment]
You could try whether you can retrieve the file using requests only. I think that's the part that is failing:

resp = requests.get(url=url)

**Comment by RishabAgr** [comment]
I tried sending the request using Postman, and going to the URL using my browser window, but even with those I keep getting timeout messages.

**Comment by andrewRowlinson** [comment]
I'm closing this as I suspect the error isn't related to mplsoccer.
